package com.mobiera.commons.enums;

public enum WidgetType {
	TEXT, HEX_TEXT, TEXTAREA, SELECT, DYNAMIC_SELECT, 
	HIDDEN, DATE, CHECKBOX, SELECT_MULTIPLE, DYNAMIC_SELECT_MULTIPLE, TABLE, MEDIA, SPECIAL, DATETIME, 
	PASSWORD_TEXT, PASSWORD_TEXTAREA, PASSWORD_HEX_TEXT, BAG
}
